### ISSUE TITLE
Node attribute needs to also store who set it and when

### ISSUE THREAD

**Issue by cfelde** [cfelde/AKAP#1]

**Comment by cfelde** [comment]
Thinking this could simply be events..

**Comment by mohamedelshami** [comment]
And reading the node data by doing a look up on transaction log against the last time stamp?

**Comment by cfelde** [comment]
Reading node attribute meta data from looking up events on the transaction log, yes. If for example the nodeId is indexed on the event, this becomes easy to filter on.

**Comment by cfelde** [comment]
Completed by #8
