### ISSUE TITLE
Implement example use cases

### ISSUE THREAD

**Issue by cfelde** [cfelde/AKAP#3]
Various example apps and use cases should be made available that use and interact with AKAP.

These can live in separate projects/repos.

List of ideas (more welcome):

- Web client for interacting with AKAP
- URL shortener
- Contract registration example

**Comment by mohamedelshami** [comment]
First example here https://github.com/mohamedelshami/AKAP-examples/tree/master/akap-url-shortner.

Let's look at possibly moving it to the master repo.

**Comment by cfelde** [comment]
Looking good, I'll need to spend some time to dive into the details.

You should move it to it's own repo, call it akap-url-shortner or similar, instead of having it under AKAP-examples. It will just be confusing to have multiple apps in one repo, and also equally confusing to have example apps in AKAP repo.

For ref, I've just created https://github.com/cfelde/AKAP-browser and will use that to put an AKAP browser web app into.

**Comment by mohamedelshami** [comment]
Ok, it's here now https://github.com/mohamedelshami/AKAP-url-shortener.

There are few improvements and some error handling testing to add. Also, I might look into enhancing the events to include timestamp index to easily retrieve events within range.

**Comment by cfelde** [comment]
Working on https://github.com/cfelde/AKAP-utils

**Comment by cfelde** [comment]
We've got a few now, with the url shortener, AKAP utils, and the Million DAI Website. More can always be added, but the issue can be closed I think.
