### ISSUE TITLE
Expose a public setTokenURI

### ISSUE THREAD

**Issue by cfelde** [cfelde/AKAP#5]
Delegates to _setTokenURI after asserting correct owner/approver

**Comment by mohamedelshami** [comment]
This should follow the same pattern of updating node attribute, where tokenId is the nodeId. For the method signature, from an API perspective uint looks cleaner. But for consistency, we might need to use uint256. Both uint and uint are the same anyways.  

 function setTokenURI(uint nodeId, string calldata uri) external onlyApproved(nodeId) {
        nodes[nodeId].tokenURI = uri;
        _setTokenURI(nodeId, uri);
    }

**Comment by cfelde** [comment]
Besides the nodes[..].tokenURI assignment this is what you'd want, see my PR comments.

**Comment by cfelde** [comment]
Fixed by @mohamedelshami commit #6
